// lib/wordlist.js — v0.7.0
// 自建英文词表（512 词），用于备份短语（助记词）。
// 注意：这不是严格 BIP39 标准词表，只用于本地离线加密备份的短语生成/校验。
// 512 词 → 每词 9 bit 熵；14 词 ≈ 126 bit，足够安全。
export const WORDLIST = [
  'able', 'about', 'above', 'acid', 'acorn', 'actor', 'adapt', 'admit',
  'adopt', 'adult', 'agent', 'agree', 'ahead', 'aim', 'alarm', 'album',
  'alert', 'alien', 'alike', 'alive', 'alley', 'allow', 'alloy', 'almond',
  'alone', 'along', 'alpha', 'alter', 'amber', 'amend', 'amuse', 'angel',
  'anger', 'angle', 'ankle', 'apart', 'apple', 'apply', 'apron', 'arbor',
  'arch', 'arena', 'argue', 'armor', 'array', 'arrow', 'ash', 'aside',
  'asset', 'atlas', 'atom', 'attic', 'audio', 'audit', 'aunt', 'avoid',
  'awake', 'award', 'aware', 'awful', 'axis', 'bacon', 'badge', 'bagel',
  'baker', 'balance', 'bamboo', 'banjo', 'barge', 'basil', 'basin', 'batch',
  'beach', 'beacon', 'beam', 'bean', 'bear', 'beast', 'beaver', 'beetle',
  'begin', 'being', 'bench', 'berry', 'bird', 'birth', 'bison', 'black',
  'blade', 'blame', 'blank', 'blast', 'blaze', 'bleak', 'blend', 'bless',
  'blink', 'block', 'bloom', 'blue', 'blush', 'board', 'boast', 'boat',
  'bold', 'bolt', 'bond', 'bone', 'bonus', 'book', 'boost', 'booth',
  'border', 'boss', 'bother', 'bottle', 'bounce', 'bound', 'bowl', 'brace',
  'brain', 'brake', 'branch', 'brand', 'brave', 'bread', 'break', 'breeze',
  'brick', 'bride', 'brief', 'bright', 'bring', 'brisk', 'broad', 'bronze',
  'brook', 'broom', 'brown', 'brush', 'bubble', 'buddy', 'budget', 'buffalo',
  'build', 'bulb', 'bunch', 'bundle', 'burst', 'bush', 'butter', 'button',
  'buyer', 'cabin', 'cable', 'cactus', 'cage', 'cake', 'camel', 'camera',
  'camp', 'canal', 'candle', 'candy', 'canoe', 'canvas', 'canyon', 'cape',
  'card', 'cargo', 'carol', 'carpet', 'carry', 'carve', 'cash', 'castle',
  'catch', 'cave', 'cedar', 'cell', 'cement', 'cereal', 'chain', 'chair',
  'chalk', 'chance', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check',
  'cheer', 'cheese', 'cherry', 'chess', 'chest', 'chief', 'child', 'chili',
  'chime', 'china', 'chip', 'choice', 'chorus', 'chunk', 'cider', 'cigar',
  'circle', 'city', 'civil', 'claim', 'clamp', 'clap', 'clash', 'class',
  'claw', 'clay', 'clean', 'clear', 'clerk', 'click', 'cliff', 'climb',
  'clip', 'cloak', 'clock', 'clone', 'close', 'cloth', 'cloud', 'clover',
  'clown', 'club', 'clue', 'coach', 'coal', 'coast', 'coat', 'cobra',
  'cocoa', 'coffee', 'coin', 'cola', 'cold', 'collar', 'color', 'colt',
  'comet', 'comic', 'coral', 'corn', 'cost', 'cotton', 'couch', 'cough',
  'count', 'court', 'cover', 'cozy', 'crab', 'crack', 'craft', 'crane',
  'crash', 'crate', 'crawl', 'crazy', 'cream', 'creek', 'crest', 'crew',
  'crisp', 'crop', 'cross', 'crowd', 'crown', 'cruise', 'crumb', 'crush',
  'crust', 'cube', 'cup', 'curl', 'curve', 'cycle', 'daily', 'dairy',
  'daisy', 'dance', 'dark', 'dart', 'dawn', 'deal', 'dear', 'debate',
  'decay', 'deck', 'deer', 'delay', 'delta', 'dense', 'depth', 'desert',
  'design', 'desk', 'dial', 'diary', 'dice', 'diet', 'dig', 'diner',
  'ditch', 'dive', 'dizzy', 'dock', 'dodge', 'dog', 'doll', 'dolphin',
  'donkey', 'donut', 'door', 'dose', 'dot', 'double', 'dough', 'dove',
  'draft', 'drag', 'drain', 'drama', 'draw', 'dream', 'dress', 'drift',
  'drill', 'drink', 'drive', 'drop', 'drum', 'dry', 'duck', 'dune',
  'dusk', 'dust', 'eagle', 'early', 'earth', 'ease', 'east', 'echo',
  'edge', 'eel', 'egg', 'eight', 'elbow', 'elder', 'elf', 'elite',
  'elm', 'ember', 'empty', 'enact', 'endow', 'energy', 'enjoy', 'enter',
  'entry', 'equal', 'error', 'erupt', 'essay', 'event', 'every', 'exact',
  'exam', 'exile', 'exist', 'extra', 'fable', 'face', 'fact', 'fade',
  'fair', 'faith', 'fall', 'false', 'fancy', 'farm', 'fast', 'fatal',
  'fault', 'favor', 'feast', 'feather', 'fence', 'fern', 'ferry', 'fetch',
  'fever', 'fiber', 'field', 'fig', 'filet', 'film', 'final', 'finch',
  'find', 'fine', 'finger', 'fire', 'first', 'fish', 'fist', 'five',
  'flag', 'flame', 'flash', 'flask', 'flat', 'flavor', 'flee', 'fleet',
  'flesh', 'float', 'flock', 'flood', 'floor', 'flour', 'flow', 'fluid',
  'flute', 'foam', 'focus', 'fog', 'foil', 'fold', 'folk', 'font',
  'food', 'fool', 'foot', 'force', 'forest', 'fork', 'form', 'fort',
  'forum', 'found', 'fox', 'frame', 'free', 'fresh', 'fried', 'frost',
  'fruit', 'fudge', 'fuel', 'fun', 'fur', 'gadget', 'gala', 'gallon',
  'game', 'gap', 'garden', 'garlic', 'gate', 'gauge', 'gaze', 'gear',
  'gecko', 'gem', 'genre', 'ghost', 'giant', 'gift', 'ginger', 'giraffe',
  'girl', 'given', 'glad', 'glance', 'glass', 'gleam', 'glide', 'globe',
  'gloom', 'glory', 'glove', 'glow', 'glue', 'goat', 'gold', 'golf',
  'goose', 'gorge', 'gospel', 'grace', 'grain', 'grand', 'grape', 'grass',
  'gravel', 'gray', 'green', 'greet', 'grid', 'grill', 'grin', 'grip',
];

export const WORDLIST_SET = new Set(WORDLIST);
export const WORDLIST_SIZE = WORDLIST.length;

export default WORDLIST;
